// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Krateo Support",
            "url": "https://krateo.io",
            "email": "contact@krateoplatformops.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/{organization}/{project}/pipelines/pipelinepermissions/{resourceType}/{resourceId}": {
            "get": {
                "description": "Get",
                "produces": [
                    "application/json"
                ],
                "summary": "Get the pipeline permission of a resource",
                "operationId": "get-pipelinepermission",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization name",
                        "name": "organization",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Project name",
                        "name": "project",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Resource type (e.g., pipelines, repositories)",
                        "name": "resourceType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Resource ID (e.g., pipeline ID, repository ID)",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "API version (e.g., 7.2-preview.1)",
                        "name": "api-version",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Basic Auth header (Basic \u003cbase64-encoded-username:password\u003e)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Pipeline permission details",
                        "schema": {
                            "$ref": "#/definitions/pipelinepermission.ResourcePipelinePermissions"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "pipelinepermission.IdentityRef": {
            "type": "object",
            "properties": {
                "_links": {
                    "$ref": "#/definitions/pipelinepermission.ReferenceLinks"
                },
                "descriptor": {
                    "type": "string"
                },
                "directoryAlias": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "imageUrl": {
                    "type": "string"
                },
                "inactive": {
                    "type": "boolean"
                },
                "isAadIdentity": {
                    "type": "boolean"
                },
                "isContainer": {
                    "type": "boolean"
                },
                "isDeletedInOrigin": {
                    "type": "boolean"
                },
                "profileUrl": {
                    "type": "string"
                },
                "uniqueName": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "pipelinepermission.Permission": {
            "type": "object",
            "properties": {
                "authorized": {
                    "type": "boolean"
                },
                "authorizedBy": {
                    "$ref": "#/definitions/pipelinepermission.IdentityRef"
                },
                "authorizedOn": {
                    "type": "string"
                }
            }
        },
        "pipelinepermission.PipelinePermission": {
            "type": "object",
            "properties": {
                "authorized": {
                    "type": "boolean"
                },
                "authorizedBy": {
                    "$ref": "#/definitions/pipelinepermission.IdentityRef"
                },
                "authorizedOn": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "pipelinepermission.ReferenceLinks": {
            "type": "object",
            "properties": {
                "links": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "pipelinepermission.Resource": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "pipelinepermission.ResourcePipelinePermissions": {
            "type": "object",
            "properties": {
                "allPipelines": {
                    "$ref": "#/definitions/pipelinepermission.Permission"
                },
                "pipelines": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pipelinepermission.PipelinePermission"
                    }
                },
                "resource": {
                    "$ref": "#/definitions/pipelinepermission.Resource"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "basic"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Azure DevOps Plugin API for Krateo Operator Generator (KOG)",
	Description:      "Simple wrapper around Azure DevOps API to provide consisentency of API response for Krateo Operator Generator (KOG)",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
