// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Krateo Support",
            "url": "https://krateo.io",
            "email": "contact@krateoplatformops.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/{organization}/{projectId}/git/repositories": {
            "post": {
                "description": "Create a new GitRepository on Azure DevOps using the provided organization, project, and repository details.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create a new GitRepository on Azure DevOps",
                "operationId": "post-gitrepository",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization name",
                        "name": "organization",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Project ID or name",
                        "name": "projectId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "API version (e.g., 7.2-preview.2)",
                        "name": "api-version",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Specify the source refs to use while creating a fork repo",
                        "name": "sourceRef",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Basic Auth header (Basic \u003cbase64-encoded-username:password\u003e)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "GitRepository creation request body (with additional fields handled by the plugin)",
                        "name": "gitrepositoryCreate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/gitrepository.CreateRepositoryRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "GitRepository details",
                        "schema": {
                            "$ref": "#/definitions/gitrepository.CreateRepositoryResponse"
                        }
                    },
                    "202": {
                        "description": "GitRepository details (repo created but creation of branch deisgnated as default branch is pending, user must create it, then the gitrepository-controller will update the default branch later)",
                        "schema": {
                            "$ref": "#/definitions/gitrepository.CreateRepositoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            }
        },
        "/api/{organization}/{project}/pipelines/pipelinepermissions/{resourceType}/{resourceId}": {
            "get": {
                "description": "Get",
                "produces": [
                    "application/json"
                ],
                "summary": "Get the pipeline permission of a resource",
                "operationId": "get-pipelinepermission",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization name",
                        "name": "organization",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Project name",
                        "name": "project",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Resource type (e.g., pipelines, repositories)",
                        "name": "resourceType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Resource ID (e.g., pipeline ID, repository ID)",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "API version (e.g., 7.2-preview.1)",
                        "name": "api-version",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Basic Auth header (Basic \u003cbase64-encoded-username:password\u003e)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Pipeline permission details",
                        "schema": {
                            "$ref": "#/definitions/pipelinepermission.ResourcePipelinePermissions"
                        }
                    }
                }
            }
        },
        "/api/{organization}/{project}/pipelines/{id}": {
            "get": {
                "description": "Get",
                "produces": [
                    "application/json"
                ],
                "summary": "Get a pipeline",
                "operationId": "get-pipeline",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization name",
                        "name": "organization",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Project name or ID",
                        "name": "project",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Pipeline ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "API version (e.g., 7.2-preview.1)",
                        "name": "api-version",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Basic Auth header (Basic \u003cbase64-encoded-username:password\u003e)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Pipeline details",
                        "schema": {
                            "$ref": "#/definitions/pipeline.GetPipelineResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "put": {
                "description": "Update a pipeline using build definitions endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update a pipeline",
                "operationId": "put-pipeline",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization name",
                        "name": "organization",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Project name or ID",
                        "name": "project",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Pipeline ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Basic Auth header (Basic \u003cbase64-encoded-username:password\u003e)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Pipeline update request body",
                        "name": "pipelineUpdate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pipeline.UpdatePipelineRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated pipeline details",
                        "schema": {
                            "$ref": "#/definitions/pipeline.UpdatePipelineResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "delete": {
                "description": "Delete a pipeline using build definitions endpoint",
                "summary": "Delete a pipeline",
                "operationId": "delete-pipeline",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization name",
                        "name": "organization",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Project name or ID",
                        "name": "project",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Pipeline ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Basic Auth header (Basic \u003cbase64-encoded-username:password\u003e)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content - Pipeline deleted successfully"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "gitrepository.AzureDevOpsTime": {
            "type": "object",
            "properties": {
                "time.Time": {
                    "type": "string"
                }
            }
        },
        "gitrepository.CreateRepositoryRequest": {
            "type": "object",
            "properties": {
                "defaultBranch": {
                    "type": "string"
                },
                "initialize": {
                    "description": "Indicates if the repository should be initialized with an initial commit",
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "parentRepository": {
                    "$ref": "#/definitions/gitrepository.GitRepositoryRefMinimal"
                },
                "project": {
                    "$ref": "#/definitions/gitrepository.TeamProjectReferenceMinimal"
                }
            }
        },
        "gitrepository.CreateRepositoryResponse": {
            "type": "object",
            "properties": {
                "_links": {
                    "$ref": "#/definitions/gitrepository.ReferenceLinks"
                },
                "creationDate": {
                    "$ref": "#/definitions/gitrepository.AzureDevOpsTime"
                },
                "defaultBranch": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isDisabled": {
                    "type": "boolean"
                },
                "isFork": {
                    "type": "boolean"
                },
                "isInMaintenance": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "parentRepository": {
                    "$ref": "#/definitions/gitrepository.GitRepositoryRef"
                },
                "project": {
                    "$ref": "#/definitions/gitrepository.TeamProjectReference"
                },
                "remoteUrl": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "sshUrl": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "validRemoteUrls": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "webUrl": {
                    "type": "string"
                }
            }
        },
        "gitrepository.GitRepositoryRef": {
            "type": "object",
            "properties": {
                "collection": {
                    "$ref": "#/definitions/gitrepository.TeamProjectCollectionReference"
                },
                "id": {
                    "type": "string"
                },
                "isFork": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "project": {
                    "$ref": "#/definitions/gitrepository.TeamProjectReference"
                },
                "remoteUrl": {
                    "type": "string"
                },
                "sshUrl": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "gitrepository.GitRepositoryRefMinimal": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "project": {
                    "$ref": "#/definitions/gitrepository.TeamProjectReferenceMinimal"
                }
            }
        },
        "gitrepository.ProjectState": {
            "type": "string",
            "enum": [
                "deleting",
                "new",
                "wellFormed",
                "createPending",
                "all",
                "unchanged",
                "deleted"
            ],
            "x-enum-varnames": [
                "ProjectStateDeleting",
                "ProjectStateNew",
                "ProjectStateWellFormed",
                "ProjectStateCreatePending",
                "ProjectStateAll",
                "ProjectStateUnchanged",
                "ProjectStateDeleted"
            ]
        },
        "gitrepository.ProjectVisibility": {
            "type": "string",
            "enum": [
                "private",
                "public"
            ],
            "x-enum-varnames": [
                "ProjectVisibilityPrivate",
                "ProjectVisibilityPublic"
            ]
        },
        "gitrepository.ReferenceLinks": {
            "type": "object",
            "properties": {
                "links": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "gitrepository.TeamProjectCollectionReference": {
            "type": "object",
            "properties": {
                "avatarUrl": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "gitrepository.TeamProjectReference": {
            "type": "object",
            "properties": {
                "abbreviation": {
                    "type": "string"
                },
                "defaultTeamImageUrl": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lastUpdateTime": {
                    "$ref": "#/definitions/gitrepository.AzureDevOpsTime"
                },
                "name": {
                    "type": "string"
                },
                "revision": {
                    "type": "integer"
                },
                "state": {
                    "$ref": "#/definitions/gitrepository.ProjectState"
                },
                "url": {
                    "type": "string"
                },
                "visibility": {
                    "$ref": "#/definitions/gitrepository.ProjectVisibility"
                }
            }
        },
        "gitrepository.TeamProjectReferenceMinimal": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "pipeline.BuildRepository": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "Required",
                    "type": "string"
                },
                "type": {
                    "description": "Required - enum: unknown, gitHub, azureReposGit, azureReposGitHyphenated",
                    "type": "string"
                }
            }
        },
        "pipeline.GetPipelineResponse": {
            "type": "object",
            "properties": {
                "_links": {
                    "$ref": "#/definitions/pipeline.ReferenceLinks"
                },
                "configuration": {
                    "$ref": "#/definitions/pipeline.PipelineConfiguration"
                },
                "folder": {
                    "description": "Embedded fields from PipelineBase",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "revision": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "pipeline.PipelineConfiguration": {
            "type": "object",
            "properties": {
                "path": {
                    "type": "string"
                },
                "repository": {
                    "description": "Required",
                    "allOf": [
                        {
                            "$ref": "#/definitions/pipeline.BuildRepository"
                        }
                    ]
                },
                "type": {
                    "description": "enum: unknown, yaml, designerJson, justInTime, designerHyphenJson",
                    "type": "string"
                }
            }
        },
        "pipeline.PipelineConfigurationParameters": {
            "type": "object",
            "properties": {
                "path": {
                    "type": "string"
                },
                "repository": {
                    "description": "Required",
                    "allOf": [
                        {
                            "$ref": "#/definitions/pipeline.BuildRepository"
                        }
                    ]
                },
                "type": {
                    "description": "Required - enum: unknown, yaml, designerJson, justInTime, designerHyphenJson",
                    "type": "string"
                }
            }
        },
        "pipeline.ReferenceLinks": {
            "type": "object",
            "properties": {
                "links": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "pipeline.UpdatePipelineRequest": {
            "type": "object",
            "properties": {
                "configuration": {
                    "$ref": "#/definitions/pipeline.PipelineConfigurationParameters"
                },
                "folder": {
                    "type": "string"
                },
                "id": {
                    "description": "maybe to be removed since RDC does not include it",
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "revision": {
                    "type": "integer"
                }
            }
        },
        "pipeline.UpdatePipelineResponse": {
            "type": "object",
            "properties": {
                "_links": {
                    "$ref": "#/definitions/pipeline.ReferenceLinks"
                },
                "configuration": {
                    "$ref": "#/definitions/pipeline.PipelineConfiguration"
                },
                "folder": {
                    "description": "Embedded fields from PipelineBase",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "revision": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "pipelinepermission.IdentityRef": {
            "type": "object",
            "properties": {
                "_links": {
                    "$ref": "#/definitions/pipelinepermission.ReferenceLinks"
                },
                "descriptor": {
                    "type": "string"
                },
                "directoryAlias": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "imageUrl": {
                    "type": "string"
                },
                "inactive": {
                    "type": "boolean"
                },
                "isAadIdentity": {
                    "type": "boolean"
                },
                "isContainer": {
                    "type": "boolean"
                },
                "isDeletedInOrigin": {
                    "type": "boolean"
                },
                "profileUrl": {
                    "type": "string"
                },
                "uniqueName": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "pipelinepermission.Permission": {
            "type": "object",
            "properties": {
                "authorized": {
                    "type": "boolean"
                },
                "authorizedBy": {
                    "$ref": "#/definitions/pipelinepermission.IdentityRef"
                },
                "authorizedOn": {
                    "type": "string"
                }
            }
        },
        "pipelinepermission.PipelinePermission": {
            "type": "object",
            "properties": {
                "authorized": {
                    "type": "boolean"
                },
                "authorizedBy": {
                    "$ref": "#/definitions/pipelinepermission.IdentityRef"
                },
                "authorizedOn": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "pipelinepermission.ReferenceLinks": {
            "type": "object",
            "properties": {
                "links": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "pipelinepermission.Resource": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "pipelinepermission.ResourcePipelinePermissions": {
            "type": "object",
            "properties": {
                "allPipelines": {
                    "$ref": "#/definitions/pipelinepermission.Permission"
                },
                "pipelines": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pipelinepermission.PipelinePermission"
                    }
                },
                "resource": {
                    "$ref": "#/definitions/pipelinepermission.Resource"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "basic"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Azure DevOps Plugin API for Krateo Operator Generator (KOG)",
	Description:      "Simple wrapper around Azure DevOps API to provide consisentency of API response for Krateo Operator Generator (KOG)",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
