openapi: 3.0.1
info:
  title: Azure DevOps Plugin API for Krateo Operator Generator (KOG)
  description: Simple wrapper around Azure DevOps API to provide consisentency of API response for Krateo Operator Generator (KOG)
  termsOfService: http://swagger.io/terms/
  contact:
    name: Krateo Support
    url: https://krateo.io
    email: contact@krateoplatformops.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: "1.0"
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
servers:
  - url: http://localhost:8080/
paths:
  /api/{organization}/{project}/pipelines/pipelinepermissions/{resourceType}/{resourceId}:
    get:
      summary: Get the pipeline permission of a resource
      description: Get
      operationId: get-pipelinepermission
      parameters:
        - name: organization
          in: path
          description: Organization name
          required: true
          schema:
            type: string
        - name: project
          in: path
          description: Project name
          required: true
          schema:
            type: string
        - name: resourceType
          in: path
          description: Resource type (e.g., pipelines, repositories)
          required: true
          schema:
            type: string
        - name: resourceId
          in: path
          description: Resource ID (e.g., pipeline ID, repository ID)
          required: true
          schema:
            type: string
        - name: api-version
          in: query
          description: API version (e.g., 7.2-preview.1)
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          description: Basic Auth header (Basic <base64-encoded-username:password>)
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Pipeline permission details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pipelinepermission.ResourcePipelinePermissions'
components:
  schemas:
    pipelinepermission.IdentityRef:
      type: object
      properties:
        _links:
          $ref: '#/components/schemas/pipelinepermission.ReferenceLinks'
        descriptor:
          type: string
        directoryAlias:
          type: string
        displayName:
          type: string
        id:
          type: string
        imageUrl:
          type: string
        inactive:
          type: boolean
        isAadIdentity:
          type: boolean
        isContainer:
          type: boolean
        isDeletedInOrigin:
          type: boolean
        profileUrl:
          type: string
        uniqueName:
          type: string
        url:
          type: string
    pipelinepermission.Permission:
      type: object
      properties:
        authorized:
          type: boolean
        authorizedBy:
          $ref: '#/components/schemas/pipelinepermission.IdentityRef'
        authorizedOn:
          type: string
    pipelinepermission.PipelinePermission:
      type: object
      properties:
        authorized:
          type: boolean
        authorizedBy:
          $ref: '#/components/schemas/pipelinepermission.IdentityRef'
        authorizedOn:
          type: string
        id:
          type: integer
    pipelinepermission.ReferenceLinks:
      type: object
      properties:
        links:
          type: object
          additionalProperties: true
    pipelinepermission.Resource:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        type:
          type: string
    pipelinepermission.ResourcePipelinePermissions:
      type: object
      properties:
        allPipelines:
          $ref: '#/components/schemas/pipelinepermission.Permission'
        pipelines:
          type: array
          items:
            $ref: '#/components/schemas/pipelinepermission.PipelinePermission'
        resource:
          $ref: '#/components/schemas/pipelinepermission.Resource'
  securitySchemes:
    Bearer:
      type: http
      scheme: basic
x-original-swagger-version: "2.0"
